name: Self-Hosted Workflow Test

on:
  push:
    branches: [ "master" ]


jobs:
  primer-paso:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: "Paso 1"
        run: echo "Vamos a imprimir la fecha y la estrcutura de archivos"
      - name: "Paso 2"
        run: date
      - name: "Paso 3"
        run: ls -la
